coverage:
  ignore:
    - Tests/ParseCertificateAuthorityTests/.*
  status:
    patch:
      default:
        target: auto
    changes: false
    project:
      default:
        target: 92
comment:
  require_changes: true
